# Generated by Django 3.1.3 on 2020-11-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201105_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='guest_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
