# Generated by Django 3.1.3 on 2020-11-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
