# Generated by Django 3.1.3 on 2020-11-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201109_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_turn', to='core.player'),
        ),
    ]
