# Generated by Django 3.1.3 on 2020-11-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_game_player_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_choice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
