# Generated by Django 3.1.3 on 2020-11-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_correct_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
