# Generated by Django 3.1.3 on 2020-11-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question'),
        ),
    ]
