# Generated by Django 3.1.3 on 2020-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201114_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
